version: '2'

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: ${MTU}

services:
  db:
    image: mysql/mysql-server:5.6
    container_name: sdnc_db_container
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
      - MYSQL_ROOT_HOST=%
    logging:
      driver: "json-file"
      options:  
        max-size: "30m"
        max-file: "5"

# Tweaking SDNC_CONFIG_DIR temporarily from ../sdnc/.. to ../appc/.. since it may be needed in this script
#    to map to SDN-C AAI Service Bundle's AAI Activator class inside the gerrit sdnc/adaptors repo, so that
#    the AAI Service bundle loads APP-C's aaiclient.properties instead of SDN-C's aaiclient.properties.
  appc:
    image: "openecomp/appc-image:latest"
    depends_on :
      - db
    container_name: appc_controller_container
    entrypoint: ["/opt/openecomp/appc/bin/startODL.sh"]
    ports:
      - "8282:8181"
      - "1830:1830"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
      - SDNC_CONFIG_DIR=/opt/openecomp/appc/data/properties
      - APPC_CONFIG_DIR=/opt/openecomp/appc/data/properties
      - DMAAP_TOPIC_ENV=SUCCESS
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"


  dgbuilder:
    image: "openecomp/dgbuilder-sdnc-image:latest"
    depends_on:
      - db
    container_name: sdnc_dgbuilder_container
    entrypoint:
       - "/bin/bash"
       - "-c"
       - "cd /opt/openecomp/sdnc/dgbuilder/ && ./start.sh sdnc1.0 && wait"
    ports:
      - "3000:3100"
    links:
      - db:dbhost
      - db:sdnctldb01
      - db:sdnctldb02
      - appc:sdnhost
    environment:
      - MYSQL_ROOT_PASSWORD=openECOMP1.0
      - SDNC_CONFIG_DIR=/opt/openecomp/sdnc/data/properties
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"

